### ISSUE TITLE
Not work on iOS 15

### ISSUE THREAD

**Issue by lucamancusodev** [k-yle/rtsp-relay#103]
After iOS 15 upgrade not work anymore (tried on android/pc without problem).

I tried to open dev console on iOS using safari and these are the error messages:

![immagine](https://user-images.githubusercontent.com/41821623/136906905-36fd7066-0e3e-4a3b-b112-2f81e9b10a10.png)

Is possible that apple blocked some protocols?

**Comment by Luccio96** [comment]
Found it, for some reason iOS wants full key chain not only key.pem and cert.pem: testing with "openssl s_client  -connect server:port"
returns "error:num=20:unable to get local issuer certificate"

So in my case, I have to **include the key.pem and fullchain.pem** (issued by let's encrypt) 

You may want to edit your SSL example.
