### ISSUE TITLE
Kill function doesn't return if there is no clientleft

### ISSUE THREAD

**Issue by bengchet** [k-yle/rtsp-relay#111]
Hi, first of all thanks for your effort for this library.

I am currently developing with verbose turning on, I discovered that when there are no clients left to connect to particular stream, it still come out the message **there are still some clients so not destroying stream**.

Problem might comes from kill function doesn't return if there is no client left.

It is not a big deal actually and it doesn't affect the whole thing, just that putting return statement will not confuse those who have turned the verbose on.

![image](https://user-images.githubusercontent.com/13192939/140002207-0645f092-c61b-4388-a99f-3d75eca3ac87.png)

Correct me if I was wrong about this. Thanks.

**Comment by k-yle** [comment]
thanks for noticing this @bengchet! I've fixed the issue in version `1.6.1`
