### ISSUE TITLE
Win10: npm i error

### ISSUE THREAD

**Issue by baur** [k-yle/rtsp-relay#13]
``
npm i rtsp-relay
 ...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rtsp-relay@1.1.0 postinstall: `chmod u+x test/rtsp-simple-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rtsp-relay@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by k-yle** [comment]
fixes and released in `v1.1.1`, sorry
