### ISSUE TITLE
How can I add cameras dynamically?

### ISSUE THREAD

**Issue by mmdjiji** [k-yle/rtsp-relay#158]
I want to use this module to make a camera proxy service, but I have many cameras and I just watch less than four of them at the same time. So if there is a method to start a ws://xxx/camera1 dynamically and stop it when I want, please teach me, thanks.

I know a method but what I mean isn't that:
```js
app.ws('/api/stream/:cameraIP', (ws, req) =>
  proxy({
    url: `rtsp://${req.params.cameraIP}:554/feed`,
  })(ws),
);
```

I wish to have a method to manage the memory dynamically, so that there wouldn't load so many cameras at the same time(memory & CPU wasting).

**Comment by k-yle** [comment]
Hi, if no one is watching the stream for a paticular camera, that stream is automatically killed to save resources. You don't need to worry about manually starting and stopping streams, this module handles that for you. 

To see how this works, you can add `verbose: true` to the options. This will print information to the console about which streams are currently active.

**Comment by mmdjiji** [comment]
Thanks, your explain is really helpful
