### ISSUE TITLE
Creating original quality of RTSP streaming 

### ISSUE THREAD

**Issue by hongson23** [k-yle/rtsp-relay#16]
Hello @k-yle,

Thank for your works, 

I would like to create a web page which is going to keep original quality of RTSP. Currently with this config 
'mpegts',
'-codec:v',
'mpeg1video',
That seem to be not enough quality of image. Can you give me some suggestions?
Thank so much!

**Comment by k-yle** [comment]
Hi, unless you have a gigabit network, you will struggle to get the original quality.


you could try changing your jsmpeg config to:

```js
  canvas: document.querySelector('canvas'),
  videoBufferSize: 1024 ** 2,
```

however this is inefficient and not advised.




By default we use the original size of the video feed. you can control this by specifying the following:
```js
additionalFlags: ['-s', '1920x1080']
```

However, the quality is handled automatically by jsmpeg which decodes the mpeg1 stream. When streaming over websockets, jsmpeg ignores timestamps and will gladly drop frames to keep up with the video.

You can read more [here](https://github.com/phoboslab/jsmpeg#performance-considerations)

**Comment by hongson23** [comment]
hello @k-yle ,

I added additionalFlags: ['-q', '1'] then mpegts worked well
followed by https://github.com/phoboslab/jsmpeg/issues/140
thank you

**Comment by k-yle** [comment]
thanks for the tip @hongson23, i'll add it to the readme in case it helps anyone else
