### ISSUE TITLE
Web-socket server and ffmpeg generated HTTP stream run on difference network system  

### ISSUE THREAD

**Issue by hongson23** [k-yle/rtsp-relay#17]
Hello @k-yle, 
I would like to deploy web-socket server on public Internet that run on difference camera network systems (LAN)
My camera systems is located in LAN which  prevents the public Internet from connecting into my local network
So i can not deploy web-socket server run on same network system with camera or NAT camera system out to Internet because our proxy
I read some information about jsmpeg from https://github.com/phoboslab/jsmpeg 

"JSMpeg comes with a tiny WebSocket "relay", written in Node.js. This server accepts an MPEG-TS source over HTTP and serves it via WebSocket to all connecting Browsers. The incoming HTTP stream can be generated using ffmpeg, gstreamer or by other means.
The split between the source and the WebSocket relay is necessary, because ffmpeg doesn't speak the WebSocket protocol. However, this split also allows you to install the WebSocket relay on a public server and share your stream on the Internet (typically NAT in your router prevents the public Internet from connecting into your local network)"

Can you support this feature in this repo?
1. ffmpeg generated HTTP stream which is deployed in same network system (LAN)
2.  send output to the web-socket server on Internet 

many thanks,

**Comment by k-yle** [comment]
Hi @hongson23, what you're describing is exactly what this module currently does. It's a relay that retransmits packets from ffmpeg to client devices via a websocket. 

> My camera systems is located in LAN which prevents the public Internet from connecting into my local network

If you want your cameras to be visible over the internet, you need to configure your network infrastructure to open up ports / forward ports so that the express server that this module generates is available via a public IP address.

**Comment by hongson23** [comment]
Thank you for your answers!

In your sample code, I see that ffmpeg transmits packets to web-socket server but both of them is configured in same local network so we must to open web-socket server port and our policy did not accept this action
I mean web-socket server is located outside LAN (ex: 123.25.218.119 static ip which is available on the Internet)
Then ffmpeg will transmit packets from LAN to web-sockets server (123.25.218.119)

**Comment by hongson23** [comment]
Hello @k-yle pls give me some information if this feature is supported. I think we need to have 2 scripts 
- Script will create web-socket server on server side which have static ip, available on Internet
- script ffmpeg  transmit packets from LAN to web-sockets server 
thanks

**Comment by k-yle** [comment]
@hongson23 having another server in between the client and the original RTSP stream will degrade the performance and quality of the stream.

I'm not sure if what you're suggesting is practicable using this module

**Comment by hongson23** [comment]
OK, thanh you so much!
