### ISSUE TITLE
Blank Screen on the index page (need help)

### ISSUE THREAD

**Issue by keanallen** [k-yle/rtsp-relay#187]
Hi, i try to run the basic example in the repo. but mine is just a blank screen.
![image](https://user-images.githubusercontent.com/45480782/206082249-0a7a25ea-d002-42d0-a886-f54992840dfe.png)

**Comment by keanallen** [comment]
yes sir. I tried my rtsp in vlc and works fine.

Here's what I did:

```
npm init -y
npm install -S rtsp-relay express
Copied the example in the readme

node app.js
```

**Comment by keanallen** [comment]
Additional photos:
![image](https://user-images.githubusercontent.com/45480782/206105587-4dd37d53-6153-4af8-9f46-b3ed288632c4.png)
![image](https://user-images.githubusercontent.com/45480782/206105642-011a862c-4231-4243-8efc-f138d9a3882c.png)
![image](https://user-images.githubusercontent.com/45480782/206105705-998c4c43-99b7-471f-bc5e-52cd3c829325.png)

**Comment by keanallen** [comment]
any update on this?

**Comment by marco-bertelli** [comment]
same issue here

**Comment by hema-001** [comment]
@keanallen @marco-bertelli 
Change `verbose: true` and see the problem, if you get something like "Stream died" then it's probably something wrong with the URL, I had the same issue at the beginning then I had to change the URL provided from my IP camera phone app for connection.

I was first trying to use the same URL I used to connect via the browser using the local area network which is 192.168.1.26:8080.
But this didn't work on the node server and `rtsp-relay`, I kept getting "Stream died" error.
Then I realized that the IP camera app on my phone had several options for connection, I used the `rtsp/h264` rule, which is `rtsp://ip:port/h264_pcm.sdp`, and it worked fine. 

The main point here is, you should find and try different URLs available for connection on your camera/phone app side.

**Comment by keanallen** [comment]
It works suddenly. Maybe we adjusted some video settings from our DVR.
