### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by tobitoi** [k-yle/rtsp-relay#188]
i use webpack and vuetify and got this error, please help
<img width="817" alt="Screenshot 2022-12-08 at 17 31 54" src="https://user-images.githubusercontent.com/20135081/206410657-243db1af-8809-4c0d-96c7-be8778d6a8bd.png">
<img width="452" alt="Screenshot 2022-12-08 at 17 32 49" src="https://user-images.githubusercontent.com/20135081/206410673-9c073c2b-5385-482e-adeb-40b28c9332d6.png">

**Comment by tobitoi** [comment]
update webpack config 

const path = require('path')
const webpack = require('webpack')
const vueConfig = require('./vue-loader.config')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin')

const isProd = process.env.NODE_ENV === 'production'
const resolve = (file) => path.resolve(__dirname, file)

module.exports = {
  devtool: isProd
    ? false
    : '#cheap-module-source-map',
  output: {
    path: resolve('../public'),
    publicPath: '/public/',
    filename: '[name].[chunkhash].js'
  },
  resolve: {
    extensions: ['*', '.js', '.json', '.vue'],
    alias: {
      'assets': resolve('../assets'),
      'components': resolve('../components'),
      'examples': resolve('../pages/examples'),
      'layouts': resolve('../layouts'),
      'mixins': resolve('../mixins'),
      'pages': resolve('../pages'),
      'public': resolve('../public'),
      'router': resolve('../router'),
      'static': resolve('../static'),
      'store': resolve('../store'),
      'vue$': 'vue/dist/vue.common.js'
    }
  },
  module: {
    noParse: /es6-promise\.js$/, // avoid webpack shimming process
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueConfig
      },
      {
        test: /\.(js|jsx)$/,
        loader: 'babel-loader',
        exclude: [/node_modules/, /ffmpeg/],
      },
      {
        test: /\.css$/,
        loader: ['vue-style-loader', 'css-loader']
      },
      {
        test: /\.styl$/,
        loader: ['vue-style-loader', 'css-loader', 'stylus-loader']
      },
      {
        test: /\.(png|jpe?g|gif|svg|jsmpe?g|Player)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: 'img/[name].[hash:7].[ext]'
        }
      }
    ]
  },
  
  performance: {
    maxEntrypointSize: 300000,
    hints: isProd ? 'warning' : false
  },
  plugins: isProd
    ? [
        new webpack.optimize.UglifyJsPlugin({
          compress: { warnings: false }
        }),
        new ExtractTextPlugin({
          filename: 'common.[chunkhash].css'
        }),
        new OptimizeCssAssetsPlugin({
          assetNameRegExp: /\.css$/
        })
      ]
    : [
        new FriendlyErrorsPlugin()
      ]
}

**Comment by tobitoi** [comment]
update webpack config 
![Uploading Screenshot 2022-12-08 at 17.34.35.png…]()

**Comment by k-yle** [comment]
The error says `Unexpected __________ token (35:4)` (it's cropped out of your screenshot). [Line 35 is this](https://github.com/k-yle/rtsp-relay/blob/main/browser/index.js#L35), which uses the JS spread operator, which has been [supported by major browsers since 2014](https://caniuse.com/mdn-javascript_operators_spread) and officially supported since ES2018. So you probably need to change your config to target ES2018, or change `babel-loader` to not exclude `node_modules/rtsp-relay`

**Comment by tobitoi** [comment]
Im already to not exclude but got same error, can you take a look this code ?

https://github.com/chuycepeda/vuetify-boilerplate

**Comment by k-yle** [comment]
Hi, the dependencies in that repository are 5 years out of date, which explains why it won't compile Javascript syntax introduced in 2018. I would suggest following the [vuetify getting start guide](https://next.vuetifyjs.com/en/getting-started/installation) to create a fresh project

**Comment by tobitoi** [comment]
> Hi, the dependencies in that repository are 5 years out of date, which explains why it won't compile Javascript syntax introduced in 2018. I would suggest following the [vuetify getting start guide](https://next.vuetifyjs.com/en/getting-started/installation) to create a fresh project

already solved using fresh project,

one more, how to rezise video like youtube

**Comment by k-yle** [comment]
> one more, how to rezise video like youtube

#137

**Comment by tobitoi** [comment]
I mean like this menu in this picture ![image](https://user-images.githubusercontent.com/20135081/207327747-c034dc44-9d92-4cfa-ad58-e7709190ecc0.jpeg)

**Comment by k-yle** [comment]
something like this would work to enable full-screen mode:
```js
const canvas = document.querySelector('canvas');
canvas.width  = window.innerWidth;
canvas.height = window.innerHeight;
canvas.requestFullscreen?.() || canvas.webkitRequestFullScreen?.() || canvas.mozRequestFullScreen?.();
```

**Comment by k-yle** [comment]
[um maybe something like this:](https://google.com/search?q=JS+detect+double+click)
```js
const canvas = document.querySelector('canvas');
canvas.addEventListener('dblclick', () => {
  // ... code from my previous comment
});
```

**Comment by tobitoi** [comment]
hello i have one issue, is possible more than 1 user access the camera forever ?

**Comment by tobitoi** [comment]
and im already try for doubleclik in vue js but not working 
<img width="789" alt="Screenshot 2022-12-23 at 19 59 49" src="https://user-images.githubusercontent.com/20135081/209333332-02b72e93-65ad-4ee5-b3b7-ee18941c1cce.png">
<img width="259" alt="Screenshot 2022-12-23 at 20 00 05" src="https://user-images.githubusercontent.com/20135081/209333341-32e2aefe-635b-4096-aab2-f97d312cc33c.png">
<img width="541" alt="Screenshot 2022-12-23 at 20 00 28" src="https://user-images.githubusercontent.com/20135081/209333343-001cec3c-c782-47f5-85bc-3b98585eb0d2.png">

**Comment by k-yle** [comment]
In Vue there are more idiomatic ways of getting a ref to the canvas instead of `document.querySelector()`. The [vue example](https://github.com/k-yle/rtsp-relay/blob/main/examples/vue.md) has a demostration of this.

**Comment by k-yle** [comment]
> hello i have one issue, is possible more than 1 user access the camera together ?

Yes. This works by default

**Comment by tobitoi** [comment]
All question already solved, thank you very much for help
