### ISSUE TITLE
Can't get a video in Laravel site using Vue components.

### ISSUE THREAD

**Issue by Kultura100** [k-yle/rtsp-relay#194]
Im starting my node.js server on port 2000 from a console without any ip host specification, after i pickup address in a web browser http://192.168.1.5:2000/ the same using localhost:2000 everything its seems to be fine, i can get a videostream using this example code.
![image](https://user-images.githubusercontent.com/94413219/216534900-840a1566-851f-44c6-b7d1-cc469e0ba8f3.png)
Which generate a working preview of camera
![image](https://user-images.githubusercontent.com/94413219/216536183-61450f54-8e63-4194-8932-8b6f69c86f9c.png)
 
But if im trying to get this working in a Vue component from a example these script generate a 'style' error.
![image](https://user-images.githubusercontent.com/94413219/216535119-cb974e88-c845-4f16-83c6-1328077acac9.png)
For setup everything im using this code below.
![image](https://user-images.githubusercontent.com/94413219/216535342-534151d2-228f-479f-9e42-d9ae6f96c078.png)
![image](https://user-images.githubusercontent.com/94413219/216535392-847a6772-b716-46fa-aec4-00d3379823ac.png)
I was trying a lot of options, for example to set a nodejs ip like:
![image](https://user-images.githubusercontent.com/94413219/216535658-8385a0b8-1311-4c61-8261-6515e653ffab.png)

But nothing seems to be working at all. Im thinking that it could be problem with Laravel Vue component access to a websocket opened by nodejs server. About a couple weeks ago i was managed to make it working, but at this point i forgot what was causing the problem, that's why im writing this issue.

**Comment by k-yle** [comment]
`this.$refs.canvas` is probably undefined. Try log it to the console. [More info about vue refs here](https://vuejs.org/guide/essentials/template-refs.html)

**Comment by Kultura100** [comment]
I didn't rebuild my asset, youre right it was undefined but now its not, the error now its undefined 'display'.
![image](https://user-images.githubusercontent.com/94413219/216561141-208eec88-ade6-4ef5-a32b-e7198961acdd.png)

**Comment by k-yle** [comment]
`this.$refs.canvas` should not be an array. 

P.S. you can click on the file name in that screenshot ([`index.js:40:54`](https://github.com/k-yle/rtsp-relay/blob/f0c7999/browser/index.js#L40)) to see exactly where the error came from

**Comment by Kultura100** [comment]
Error came from a 
![image](https://user-images.githubusercontent.com/94413219/216732910-e2febcfb-e330-40c3-81bd-154400947a4c.png)
It says that what's on screenshot above
For some reasons, devtools take's it like array but its actually,
![image](https://user-images.githubusercontent.com/94413219/216734103-d34fadc0-e76e-4289-963b-2459461240e6.png)
in promise there's a feedback of loadplayer.

**Comment by Kultura100** [comment]
The true issue was, that if you use your canvas in v-for in vue, he became a array of Canvases, it meants that if you want to get reference you need to point to this.$refs.canvas[0]
