### ISSUE TITLE
How to Kill FFMPEG Process

### ISSUE THREAD

**Issue by alfian444** [k-yle/rtsp-relay#196]
hello, i did rtsp with this code:
`
app.ws('/api/stream/:cameraIP', (ws, req) =>
  proxy({
    url: 'rtsp://${req.params.cameraIP}:554/feed',
  })(ws),
);
`

but when the client has disconnected, the FFMPEG process is still running behind, how do I stop this FFMPEG process
![image](https://user-images.githubusercontent.com/56497185/221359473-cb0ece92-ab28-43c7-819f-f6c0def4d89e.png)

**Comment by k-yle** [comment]
```js
const { proxy, scriptUrl, killAll } = require('rtsp-relay')(app);

killAll();
```

will add it to the README at some point

**Comment by alfian444** [comment]
> ```js
> const { proxy, scriptUrl, killAll } = require('rtsp-relay')(app);
> 
> killAll();
> ```
> 
> will add it to the README at some point

I want to do kill for specific ffmpeg, is that possible?

**Comment by k-yle** [comment]
If you know the [Process ID (`pid`)](https://en.wikipedia.org/wiki/Process_identifier) you could use `ps-node` directly:

```ts
const { kill } = require('ps-node');

kill(pid)
```

**Comment by alfian444** [comment]
> If you know the [Process ID (`pid`)](https://en.wikipedia.org/wiki/Process_identifier) you could use `ps-node` directly:
> 
> ```ts
> const { kill } = require('ps-node');
> 
> kill(pid)
> ```

ok thank you, I understand
