### ISSUE TITLE
Cannot stop reconnecting if the end point is not available at some point

### ISSUE THREAD

**Issue by paliuca** [k-yle/rtsp-relay#197]
loadPlayer({
                    url: this.socketUrl,
                    canvas: this.videoPlayer.nativeElement,
                    loop: false,
                    disconnectThreshold: 3000,
                    onDisconnect: () => {
                        console.log('onDisconnect');                        
                    }
                }).then((player: Player) => {
                    // here the player is available
                    // and can be destroyed if necessary
                })

How can stop the player from trying to recconect if the source is not avaialble
Thank you

**Comment by k-yle** [comment]
that's intentional, it's what youtube and other video platforms do. But if you don't want that behaviour then use `player.destroy()` and/or `player.stop()`

**Comment by paliuca** [comment]
Ok, i know, but until the connection is made succesfully, (so the socket url is responding with something), the player object is not available, so i cannot use destry or stop.
I am using it with angular and if the backend is not responding quickly or is not responding at all i cannot destroy the player and never stops trying to reconnect.

What i am suggesting is maybe the player object to be available wihtout success conection, or to be with max retries with an event.
Thank you

**Comment by k-yle** [comment]
got it, that sounds like a reasonable request. If you update to the latest version (`v1.7.0`), you can access `player` as an argument in `onDisconnect`

```diff
-   onDisconnect: () => {
+   onDisconnect: (player) => {
      console.log('onDisconnect');
+     player.destroy();
    }
```

**Comment by paliuca** [comment]
It works, Thank you so much.
