### ISSUE TITLE
How to Update FFMPEG Version

### ISSUE THREAD

**Issue by alfian444** [k-yle/rtsp-relay#235]
I checked the version on ffmpeg in this directory `/node_modules/@ffmpeg-installer/linux-x64/ffmpeg`, and I found that the ffmpeg version was ffmpeg version `N-47683-g0e8eb07980-static`. how do I update to a newer version of ffmpeg?

**Comment by k-yle** [comment]
thanks for pointing this out. The library we were using [has been abandoned](https://github.com/kribblo/node-ffmpeg-installer/discussions/52) so we were using an ancient version of ffmpeg from 2018... I've just released v1.8.0 which uses the latest version of ffmpeg
