### ISSUE TITLE
Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by alfian444** [k-yle/rtsp-relay#236]
I get an error on my browser console like the following

![image](https://github.com/k-yle/rtsp-relay/assets/56497185/cfe11b92-d444-4365-bb40-9d1b3b82f1d5)

how to solve this error?

**Comment by k-yle** [comment]
This error is coming from JSMpeg. you may want to check ou[t these issues.](https://github.com/phoboslab/jsmpeg/issues?q=is%3Aissue+memory+access+out+of+bounds)

**Comment by alfian444** [comment]
> This error is coming from JSMpeg. you may want to check ou[t these issues.](https://github.com/phoboslab/jsmpeg/issues?q=is%3Aissue+memory+access+out+of+bounds)

I have been testing for several weeks by adding videoBufferSize as follows:

`
loadPlayer({
                    videoBufferSize:10 * 1024 * 1024,
                    url:url:,
                    canvas: document.getElementById('canvas')
})
`
and the "memory access out of bounds" error does not appear

Thanks
