### ISSUE TITLE
how to play 20 cameras same time

### ISSUE THREAD

**Issue by phuctjoin** [k-yle/rtsp-relay#279]
I want to play 20 cameras same time by:
```
app.ws('/api/stream/:cameraIP', (ws, req) =>
  proxy({
    url: `rtsp://${req.params.cameraIP}:554/feed`,
  })(ws),
);
```

but it only play max 16 cams, 4 ones can't play.

I need to config something or it depend on the cpu?

**Comment by k-yle** [comment]
Streaming 20 cameras is very inefficient, it will use a huge amount of bandwidth and CPU resources.

A more efficient solution is to merge your cameras, for example using [an HDMI multiviewer](https://archive.md/wip/zJIlg), and then broadcast a single livestream feed

**Comment by phuctjoin** [comment]
> Streaming 20 cameras is very inefficient, it will use a huge amount of bandwidth and CPU resources.
> 
> A more efficient solution is to merge your cameras, for example using [an HDMI multiviewer](https://archive.md/wip/zJIlg), and then broadcast a single livestream feed

@k-yle thank you for response. I will try to check it.
