### ISSUE TITLE
Not showing RTSP stream from IP Camera Beward B1210R

### ISSUE THREAD

**Issue by baur** [k-yle/rtsp-relay#28]
Not showing RTSP stream from IP Camera Beward B1210R, but via VLC works
I can't see any error message either server console or client console
How to check: is this a decoding error or a playing error?

Other cameras are working fine!

**Comment by k-yle** [comment]
It's hard to help without knowing the intricacies of the camera, sorry. 

Have you tried setting `verbose: true` to get more information logged?

perhaps you could experiment until you have an ffmpeg command that works and then supply those arguments to this NPM module using `additionalOptions`

**Comment by baur** [comment]
Thanks you for answer, I'll be experiment ...
Can you activate git discussion tab
