### ISSUE TITLE
if you want to use this with react in front-end is it possible?

### ISSUE THREAD

**Issue by rogeliozx** [k-yle/rtsp-relay#4]
i want make little screens in react of my cams with one form,in my web its posible?

**Comment by k-yle** [comment]
I haven't tested this but you could do something like the following:

```js
import React, { useRef, useEffect } from "react";
import * as JSMpeg from 'jsmpeg';

function App() {
  const canvas = useRef();
  const player = useRef();

  useEffect(() => {
    player.current = new JSMpeg.Player(
      'ws://' + location.host + '/api/stream', 
      { canvas }
    );
  }, []);

 // interact with player.current if you need to

  return (
    <canvas ref={canvas} />
  );
}

**Comment by rogeliozx** [comment]
tanks 💃

**Comment by rogeliozx** [comment]
jsmpg.js:292 Access to XMLHttpRequest at 'ws://localhost:3001/api/stream' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
why happen this , in simple web page works good , but in react do this D:
