### ISSUE TITLE
Stream is not restored after reconnection

### ISSUE THREAD

**Issue by baur** [k-yle/rtsp-relay#43]
If the connection with the camera falls off and is restored, then the stream is not restored until restart server.js

**Comment by baur** [comment]
and is there any way to signalize client than camera not available, maybe maybe put to stream default image or video?

**Comment by k-yle** [comment]
Hi, if you're using the new `loadPlayer` method (see the updated README) you can add an extra option called `onDisconnect`:

```js
loadPlayer({
  url: 'wss://' + location.host + '/api/stream',
  canvas: document.getElementById('canvas'),

  
  onDisconnect: () => {
    console.log('Connection lost!');
  },
});
```

Then you can hide the canvas and do whatever you like. Creating a new canvas will re-create the RTSP stream. You do not need to restart the node server
