### ISSUE TITLE
Can't kill some streams if there are multiple users.

### ISSUE THREAD

**Issue by sh2** [k-yle/rtsp-relay#73]
Thank you for an great tool! 
I found that this tool can't kill some streams if there are multiple users.

```
User A: p = loadPlayer(url1); (wsServer.clients.size == 1)
User B: p = loadPlayer(url2); (wsServer.clients.size == 2)
User B: p.destroy(); (wsServer.clients.size == 1)
```

So in this situation, Inbound[url2] is never killed, and ffmpeg process still alives.
I think each InboundStreamWrapper needs its own user counter (not wsServer.clients.size).

Thanks,

**Comment by k-yle** [comment]
fixed in #74
