### ISSUE TITLE
Video quality improvement parameters doesn't work

### ISSUE THREAD

**Issue by Dipenduroy** [k-yle/rtsp-relay#75]
Hi @k-yle ,
I am using your library to broadcast multiple IP cameras using a separate route for each one. 
As per the video quality improvement options in the [link](https://github.com/k-yle/rtsp-relay#improving-the-video-quality), I tried all the options, but the video quality has no changes using those suggested parameters.
I tried another [library](https://github.com/xpcrts/Steaming-IP-Camera-Nodejs) that has better video quality, but it doesn't support multiple cameras using dynamic URL instead it requires multiple WebSocket port which is in turn not efficient.
Can you suggest changes in your library for which video quality can be improved apart from the currently given suggestions?

**Comment by k-yle** [comment]
Hi, sorry there was a typo in the README, if you try with `additionalFlags` (instead of `additionalOptions`) you might have more luck

**Comment by Dipenduroy** [comment]
Hi @k-yle,
Thanks, that worked like charm.
