### ISSUE TITLE
Stream died

### ISSUE THREAD

**Issue by stan69b** [k-yle/rtsp-relay#8]
Hello, i've been using this lib for a couple of month and all was working perfectly, but recently, i've been recieving this error message server side, even though i haven't updated my client or server in a while.

Do you happend to have an idea of what the problem might be ?

http://www.umbitchoise.com/live

i'm NOT using ssl so http:// and ws:// only.

(i'm using your code from the readme, without any changes apart from the rtsp stream which works as i tester id with vlc)

18:18:55 18|UMB - Camera  | [rtsp-relay] New WebSocket Connection
18:18:55 18|UMB - Camera  | [rtsp-relay] Creating brand new stream
18:19:06 18|UMB - Camera  | [rtsp-relay] Stream died - will recreate when the next client connects

Thanks for any tips you have :) 

<img width="844" alt="Screenshot 2020-08-15 at 18 53 25" src="https://user-images.githubusercontent.com/3304418/90317294-a64d6f80-df28-11ea-8709-e14cf10e8a16.png">

**Comment by k-yle** [comment]
Hi, I've realised that not all errors are logged, even if `verbose: true`. I've published `v1.0.6` which will now show additional logging in verbose mode.

let me know if you see any new error messages in `v1.0.6`; as they will provide more insight into why the stream died.

**Comment by stan69b** [comment]
Thanks for the update.
if i'm not mistaken, you added the `this.stream.on('error' ...` but it seems i'm not getting an error server side. most likely the clients exits the socket for some reason :( 

I'm stating to believe that browsers exit the socket if it is not secured but it's just a guess :/ 
Thanks anyway for the added logs, it did help me identify that the bug does not seem to be coming from your lib ;)

**Comment by stan69b** [comment]
Little update, we were on a very slow network for this installation and probably unstable. We switched to a fiber optics connection recently and after setting up the camera again, everything juste started working again. I cannot explain what really happened, but it was clearly not related to your tool :) 

I'm closing the issue now as it is not relevant to your program.  Thanks again for your help and your update to help me debug my setup.

**Comment by LouisKwang** [comment]
Hello, I have encountered a similar problem with you recently. Have you found a solution? Thank you for your prompt!

**Comment by phiberber** [comment]
Been having the same issue here, it was working but now it isn't

**Comment by phiberber** [comment]
So the problem with me was the Audio encoding, with AAC it works, without it doesn't.
