### ISSUE TITLE
Doesn't work, no image

### ISSUE THREAD

**Issue by sandorvasas** [k-yle/rtsp-relay#81]
Trying to connect to my DVR's RTSP server using the provided example node code. when I hit / and check the network tab, I see it makes a request to /api/stream wihch returns 101 Switching Protocols, and then a single binary buffer:
00000000: 6a73 6d70 0000 0000    
which is the jsmp header and that's all, no further data.

**Comment by k-yle** [comment]
Hi, are you accessing `/api/stream` via localhost or through a proxy/gateway/router etc.? Also HTTP/ws or HTTPS/wss? And does the same RTSP url work in VLC player?

**Comment by zhejinjiang** [comment]
i have same issue. and accessing /api/stream via localhost. same RTSP url work in VLC player.
![image](https://user-images.githubusercontent.com/89907308/163775185-6dcadfe3-99df-486b-bf5c-a0f24568a7de.png)
![image](https://user-images.githubusercontent.com/89907308/163775245-4da7ec20-852f-4c1a-9026-3992d77a8bc9.png)
Chrome/100.0.4896.60

**Comment by zhejinjiang** [comment]
emm... h265 streaming, switch to 264 is OK.

**Comment by keanallen** [comment]
> Trying to connect to my DVR's RTSP server using the provided example node code. when I hit / and check the network tab, I see it makes a request to /api/stream wihch returns 101 Switching Protocols, and then a single binary buffer: 00000000: 6a73 6d70 0000 0000 which is the jsmp header and that's all, no further data.

I have also this issue. Can someone help?
